# Use new container infrastructure to enable caching
sudo: false

language: java

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"