#%RAML 1.0 DataType

usage: provides a type that stores applicant student registered payload information

description: A applicant registered payload
properties:
  paidBy: string
  gradeName: string
  paidAmount: number