#%RAML 1.0 DataType

usage: provides a type that stores user information

description: A new applicant student
properties:
  name: !include Name.raml
  address: !include Address.raml
  grade: !include Grade.raml